apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-claim
  annotations:
    apps.open-cluster-management.io/deployables: "true"
  labels:
    app: gogs-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
